import type { TranslationKey } from './uk';

export const en = {
  // Common / Lang
  'lang.uk': 'Ukrainian',
  'lang.en': 'English',
  'lang.select': 'Interface Language',

  // Login
  'login.title': 'UNiHub',
  'login.subtitle': 'Sign in to your Moodle account',
  'login.username': 'Username',
  'login.usernameOrEmail': 'Username or email',
  'login.password': 'Password',
  'login.submit': 'Sign In',
  'login.loading': 'Signing in...',
  'login.success': 'Signed in successfully',
  'login.invalidCredentials': 'Login failed. Please check your credentials.',
  'login.enterUsernameError': 'Please enter a username',
  'login.enterPasswordError': 'Please enter a password',
  'login.showPassword': 'Show password',
  'login.hidePassword': 'Hide password',
  'login.orMoodle': 'or with Moodle login',
  'login.googleError': 'Google sign-in error',
  'login.linkMoodleTitle': 'Link Moodle Account',
  'login.linkMoodleHint':
    'To load your courses, schedule, and grades, enter your Moodle username and password. You only need to do this once — future logins will use Google in one click.',
  'login.linkMoodleUsername': 'Username or email in Moodle',
  'login.linkMoodleUsernamePlaceholder': 'Moodle username',
  'login.linkMoodlePassword': 'Password in Moodle',
  'login.linkMoodlePasswordPlaceholder': 'Password',
  'login.linkMoodleSubmit': 'Link Moodle',
  'login.linkMoodleLoading': 'Linking...',
  'login.linkMoodleBack': 'Back to Sign In',
  'login.linkMoodleSkip': 'Skip',
  'login.linkMoodleSuccess': 'Moodle account linked successfully!',
  'login.linkMoodleEnterUsername': 'Please enter username or email in Moodle',
  'login.linkMoodleEnterPassword': 'Please enter password in Moodle',
  'login.linkMoodleRequired': 'Linking a Moodle account is required to complete sign-in',
  'login.linkMoodleError': 'Failed to link account. Please check your credentials.',

  // Themes
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.cyberpunk': 'Cyberpunk',
  'theme.select': 'Theme selection',

  // Navigation (short & full)
  'nav.overview': 'Overview',
  'nav.overview.full': 'Student Card / Overview',
  'nav.courses': 'Courses',
  'nav.courses.full': 'Study Plan',
  'nav.assignments': 'Assignments',
  'nav.assignments.full': 'Assignments',
  'nav.schedule': 'Schedule',
  'nav.schedule.full': 'Class Schedule',
  'nav.grades': 'Grades',
  'nav.grades.full': 'Gradebook & Scores',
  'nav.opportunities': 'Opportunities',
  'nav.opportunities.full': 'Opportunities & Projects',

  // Sidebar & Header
  'sidebar.logout': 'Log out',
  'sidebar.moodleConnected': 'Moodle LMS (connected)',
  'header.notifications': 'Notifications',
  'header.notifications.empty': 'No notifications',
  'dashboard.sessionExpired': 'Session expired or invalid. Please sign in again.',
  'dashboard.loadError': 'Failed to load data. Please ensure the backend is running.',
  'dashboard.syncSuccess': 'Data refreshed successfully',
  'dashboard.offlineNotice': 'Using cached data: unable to connect to Moodle server.',
  'dashboard.updating': 'Updating...',
  'dashboard.dataUpdated': 'Data updated',
  'dashboard.refreshData': 'Refresh data',
  'dashboard.refresh': 'Refresh',
  'dashboard.offlineWarning': 'Warning: Moodle server is unreachable. Showing cached data',
  'dashboard.offlineFrom': 'from',
  'dashboard.linkMoodlePrompt':
    'Moodle account is not linked. Link it to load your schedule, assignments, and grades.',
  'dashboard.linkMoodleAction': 'Link Moodle',
  'common.cancel': 'Cancel',

  // Greetings
  'greeting.morning': 'Good morning',
  'greeting.day': 'Good afternoon',
  'greeting.evening': 'Good evening',
  'greeting.night': 'Good night',
  'greeting.student': 'student',
  'greeting.noDeadlines': 'No upcoming deadlines — time to relax or review courses.',
  'greeting.deadlinePrefix': '',
  'greeting.deadlineRemaining': 'due in',
  'greeting.hours': 'hrs.',
  'greeting.willMakeIt': 'Ready?',

  // Student Profile Card
  'student.fullTime': 'Full-time',
  'student.budget': 'State-funded',
  'student.scholarship': 'Honors (Academic scholarship)',
  'student.faculty': 'Faculty / Institute',
  'student.department': 'Department',
  'student.courseAndGroup': 'Year / Academic Group',
  'student.card': 'Student ID',
  'student.recordBook': 'Record Book',
  'student.credits': 'ECTS Credits Earned',
  'student.gpa': 'Grade Point Average (GPA)',
  'student.status': 'Academic Status',
  'student.statusActive': 'Enrolled (active)',

  // Stats & Overview
  'overview.totalCourses': 'Total Courses',
  'overview.pendingAssignments': 'Pending Assignments',
  'overview.gpa': 'Grade Point Average (GPA)',
  'overview.currentCourses': 'Current Courses',
  'overview.all': 'All',
  'overview.upcomingDeadlines': 'Upcoming Events & Deadlines',
  'overview.noEvents': 'No events or deadlines found',
  'overview.noCourses': 'No courses found',

  // Assignments Donut
  'donut.title': 'Assignment Status',
  'donut.empty': 'No assignments found',
  'donut.completed': 'Completed',
  'donut.awaitingReview': 'Awaiting review',
  'donut.overdue': 'Overdue',
  'donut.inProgress': 'In progress',

  // Streak
  'streak.title': 'Streak',
  'streak.day': 'day',
  'streak.daysFew': 'days',
  'streak.daysMany': 'days',

  // Courses
  'courses.instructor': 'Instructor',
  'courses.curriculumSubject': 'Individual study plan curriculum subject',
  'courses.progress': 'Completion progress',
  'courses.viewMaterials': 'View course materials',

  // Control forms
  'control.exam': 'Exam',
  'control.credit': 'Pass/Fail Credit',
  'control.diffCredit': 'Graded Credit',

  // Course Contents
  'courseContents.back': 'Back to courses',
  'courseContents.breadcrumbs': 'Courses',
  'courseContents.title': 'Course Contents',
  'courseContents.loading': 'Loading contents...',
  'courseContents.loadError': 'Failed to load course contents',
  'courseContents.empty': 'There are no materials available in this course yet.',
  'courseContents.moduleType': 'Type',

  // Grades Tab & Table
  'grades.subtitle': 'Electronic gradebook and grade simulator',
  'grades.simulatorBtn': 'Grade Simulator (What if?)',
  'grades.discipline': 'Discipline',
  'grades.colCourse': 'Discipline',
  'grades.colCredits': 'ECTS Credits',
  'grades.colControl': 'Control Form',
  'grades.colCurrent': 'Current Score (0–60)',
  'grades.colExam': 'Exam (0–40)',
  'grades.colFinal': 'Final 100-Point Grade',
  'grades.colEcts': 'ECTS Grade',
  'grades.colTraditional': 'National Grade',
  'grades.excellent': 'Excellent',
  'grades.good': 'Good',
  'grades.satisfactory': 'Satisfactory',
  'grades.unsatisfactory': 'Unsatisfactory',
  'grades.passed': 'Passed',
  'grades.failed': 'Failed',
  'grades.chartValue': 'Grade',
  'grades.chartEmpty': 'No grades found',
  'grades.defaultCourse': 'Course',

  // Grade Simulator
  'simulator.modalTitle': 'Grade Simulator — "What if?"',
  'simulator.empty': 'No grades available for simulation',
  'simulator.hint':
    'Current discipline score makes up 70% of the final. Hypothetical works make up the remaining 30%.',
  'simulator.forecast': 'Final result forecast (100-point scale & ECTS)',
  'simulator.noAssignments': 'No assignments for this discipline — showing current score',

  // Assignments Tab
  'assignments.filters': 'Filters',
  'assignments.hideFilters': 'Hide filters',
  'assignments.dateFrom': 'Date from',
  'assignments.dateTo': 'Date to',
  'assignments.oldestFirst': 'Oldest first',
  'assignments.newestFirst': 'Newest first',
  'assignments.hideCompleted': 'Hide completed',
  'assignments.deadline': 'Deadline',
  'assignments.noDueDate': 'No due date',
  'assignments.noDeadline': 'No submission deadline',
  'assignments.submittedLate': 'Submitted late',
  'assignments.grade': 'Grade',
  'assignments.open': 'Open',
  'assignments.emptyNotFound': 'No assignments found',
  'assignments.emptyDateFilter': 'No assignments found for selected dates',
  'assignments.emptyAllDone':
    'Hooray, all assignments completed! Time to relax or review lectures 🎉',

  // Schedule View
  'schedule.modeMonth': 'Month',
  'schedule.modeWeek': 'Week',
  'schedule.modeDay': 'Day',
  'schedule.viewModeAria': 'Schedule mode',
  'schedule.exportICal': 'Export to iCal',
  'schedule.prevWeek': 'Previous week',
  'schedule.nextWeek': 'Next week',
  'schedule.prevMonth': 'Previous month',
  'schedule.nextMonth': 'Next month',
  'schedule.freeDay': 'Free day',
  'schedule.scheduleFor': 'Schedule for',
  'schedule.noClasses': 'No classes for this day',
  'schedule.typeLecture': 'Lecture',
  'schedule.typeLab': 'Laboratory',
  'schedule.typePractice': 'Practical class',
  'schedule.typeExam': 'Exam',
  'schedule.typeOther': 'Consultation',

  // Header & Audio
  'header.soundMute': 'Mute sound',
  'header.soundUnmute': 'Unmute sound',
  'header.openMenu': 'Open menu',
  'header.userMenu': 'User profile menu',
  'header.unreadCount': 'new',

  // Assignment Modal
  'assignmentModal.defaultTitle': 'Assignment',
  'assignmentModal.loadingStatus': 'Loading status...',
  'assignmentModal.loadStatusError': 'Failed to load assignment status',
  'assignmentModal.openMoodle': 'Open original assignment on Moodle',
  'assignmentModal.description': 'Description',
  'assignmentModal.attachedFiles': 'Attached files',
  'assignmentModal.download': 'Download',
  'assignmentModal.submissionStatus': 'Submission status',
  'assignmentModal.status': 'Status',
  'assignmentModal.grade': 'Grade',
  'assignmentModal.noStatusData': 'No status data available',
  'assignmentModal.submitTitle': 'Submit assignment',
  'assignmentModal.answerText': 'Answer text',
  'assignmentModal.placeholder': 'Enter your submission here...',
  'assignmentModal.attachFile': 'Attach file',
  'assignmentModal.dragDrop': 'Drag and drop a file here or',
  'assignmentModal.browse': 'browse',
  'assignmentModal.cancel': 'Cancel',
  'assignmentModal.submit': 'Submit',
  'assignmentModal.uploading': 'Uploading file...',
  'assignmentModal.submitSuccess': 'Submission sent successfully',
  'assignmentModal.submitError': 'Error submitting assignment',
  'assignmentModal.formRequired': 'Please enter text or attach a file',
  'assignmentModal.statusSubmitted': 'Submitted for grading',
  'assignmentModal.statusGraded': 'Graded',
  'assignmentModal.statusNew': 'No attempt',
  'assignmentModal.statusDraft': 'Draft',

  // Gamification
  'badge.unlocked': 'Achievement',

  // Modal
  'modal.close': 'Close',

  // Dean's Office Modal
  'dean.modalTitle': "Contact Dean's Office",
  'dean.supportSubtitle': "Dean's Office and Academic Support Service",
  'dean.email': 'Email:',
  'dean.phone': 'Phone:',
  'dean.schedule': 'Hours:',
  'dean.scheduleValue': 'Mon–Fri, 09:00 – 17:00',
  'dean.telegram': 'Telegram:',
  'dean.sectionLabel': 'Common request templates:',
  'dean.subjectLabel': 'Request subject',
  'dean.subjectPlaceholder': 'Enter request subject',
  'dean.messageLabel': 'Message text or comment',
  'dean.messagePlaceholder': 'Describe the details of your request...',
  'dean.cancel': 'Cancel',
  'dean.sending': 'Sending...',
  'dean.submit': 'Send request',
  'dean.successMessage':
    "Request #DC-{ticket} successfully sent to the Dean's Office! A response will be sent to your corporate email.",
  'dean.topic.certificate': 'Certificate of Study',
  'dean.topic.transcript': 'Academic transcript / grade report',
  'dean.topic.session': 'Session and schedule questions',
  'dean.topic.individual': 'Individual study schedule',
  'dean.topic.other': "Other request to Dean's Office",

  // Quick Actions
  'quickActions.title': 'Quick Actions',
  'quickActions.moodleBadge': 'Karazin',
  'quickActions.moodleTitle': 'Open Moodle LMS platform in a new tab',
  'quickActions.moodleDescription': 'Course platform',
  'quickActions.assignmentsTitle': 'Go to assignments and deadlines',
  'quickActions.myAssignments': 'My Assignments',
  'quickActions.pendingCount': '{count} to complete',
  'quickActions.allDone': 'All assignments submitted',
  'quickActions.scheduleTitle': 'Go to class schedule',
  'quickActions.schedule': 'Class Schedule',
  'quickActions.scheduleDescription': 'Classes and consultations',
  'quickActions.deanTitle': "Contact Dean's Office for a certificate or consultation",
  'quickActions.dean': "Contact Dean's Office",
  'quickActions.deanDescription': 'Requests, certificates, contacts',
  'quickActions.ariaLabel': 'Quick Actions',

  // Recent Grades Feed
  'recentGrades.title': 'Recent Grades',
  'recentGrades.allGrades': 'All grades',
  'recentGrades.recently': 'Recently',
  'recentGrades.passed': 'Passed',
  'recentGrades.empty': 'No graded assignments yet',
  'recentGrades.allGradesTitle': 'View all grades in the gradebook',
  'recentGrades.ariaLabel': 'Recent Grades',
  'recentGrades.viewAssignment': 'Go to assignment: {name}',

  // Overview Tab Extras
  'overview.joinMeeting': 'Join meeting',
  'overview.coursesHint': 'View courses →',
  'overview.assignmentsHint': 'View assignments →',
  'overview.gradesHint': 'Gradebook →',
  'overview.nearestDeadline': 'Nearest deadline:',
  'overview.specialty': 'Specialty',
  'overview.noDeadline': 'No deadline',
  'overview.coursesTitle': 'Go to courses list',
  'overview.assignmentsTitle': 'Go to assignments list',
  'overview.gradesTitle': 'Go to gradebook and grades',
  'overview.viewCourseMaterials': 'View course materials: {name}',
  'student.courseGroupFormat': 'Year {course}, group {group}',

  // Opportunities
  'opportunities.tabs.catalog': 'Catalog',
  'opportunities.tabs.myOpportunities': 'My Opportunities',
  'opportunities.tabs.myApplications': 'My Applications',
  'opportunities.tabs.moderation': 'Moderation',
  'opportunities.actions.create': 'Create Opportunity',
  'opportunities.toast.createdDraft': 'Opportunity successfully created as a draft!',
  'opportunities.toast.createError': 'Error creating opportunity',
  'opportunities.toast.applySuccess': 'Your application was successfully sent to the organizer!',
  'opportunities.toast.applyError': 'Failed to submit application',
  'opportunities.toast.sentToReview': 'Opportunity sent for moderation!',
  'opportunities.toast.genericError': 'Error',
  'opportunities.toast.stateUpdated': 'Project state updated',
  'opportunities.toast.statusUpdateError': 'Error updating status',
  'opportunities.confirm.withdraw': 'Are you sure you want to withdraw your application?',
  'opportunities.toast.withdrawn': 'Application withdrawn',
  'opportunities.toast.approved': 'Opportunity approved and published in the catalog!',
  'opportunities.toast.rejected': 'Opportunity rejected',
  'opportunities.toast.requiresChanges': 'Opportunity returned to the author for revision',
  'opportunities.toast.moderateError': 'Moderation error',
  'opportunities.card.defaultOwner': 'Karazin University',
  'opportunities.card.vacancy': 'Vacancy',
  'opportunities.card.practice': 'Practice',
  'opportunities.card.paidDefault': 'Paid',
  'opportunities.card.experience': 'Experience / Practice',
  'opportunities.card.moderatorNote': 'Moderator note:',
  'opportunities.card.applications': 'Applications',
  'opportunities.card.management': 'Management',
  'opportunities.card.details': 'Details',
  'opportunities.card.detailsAria': 'More details about {title}',
} as const satisfies Record<TranslationKey, string>;
