import type { StudentProfile, CurriculumItem } from '@core/types';

export const fallbackStudentProfile: StudentProfile = {
  id: 'karazin-student-001',
  moodleId: 4021,
  fullName: 'Барсуков Родіон Сергійович',
  email: 'rodion.barsukov@karazin.ua',
  avatarUrl: 'https://moodle.universemvp.tech/user/pix.php/4021/f1.jpg',
  studentCardNumber: 'KB-10293847',
  recordBookNumber: 'ЗК-2024-042',
  faculty: 'ННІ Компʼютерних наук та штучного інтелекту',
  department: 'Кафедра математичного моделювання та аналізу даних',
  specialty: '122 Компʼютерні науки',
  educationalProgram: 'Компʼютерні науки та інтелектуальні системи',
  degree: 'bachelor',
  course: 3,
  group: 'КС12',
  studyForm: 'full-time',
  financing: 'budget',
  status: 'active',
  gpa: 92.4,
  totalCreditsEarned: 120,
  academicStanding: 'honors',
};

export const mockKarazinCurriculum: CurriculumItem[] = [
  {
    id: 101,
    code: 'CS301',
    name: 'Паралельні та розподілені обчислення',
    shortName: 'ПРО',
    fullname: 'Паралельні та розподілені обчислення',
    shortname: 'ПРО',
    description:
      'Архітектура паралельних обчислювальних систем, моделі OpenMP та MPI, багатопотоковість у C++.',
    credits: 5,
    semester: 5,
    academicYear: '2026/2027',
    cycle: 'professional',
    controlType: 'exam',
    instructors: [{ name: 'Проф. Коваленко О. І.', email: 'kovalenko@karazin.ua', role: 'Лектор' }],
    status: 'in_progress',
    progress: 75,
  },
  {
    id: 102,
    code: 'CS302',
    name: 'Алгоритми та структури даних',
    shortName: 'АСД',
    fullname: 'Алгоритми та структури даних',
    shortname: 'АСД',
    description:
      'Асимптотичний аналіз, динамічне програмування, дерева пошуку, графи та обчислювальна складність.',
    credits: 5,
    semester: 5,
    academicYear: '2026/2027',
    cycle: 'professional',
    controlType: 'exam',
    instructors: [{ name: 'Доц. Барсуков С. М.', email: 'barsukov.sm@karazin.ua', role: 'Лектор' }],
    status: 'in_progress',
    progress: 88,
  },
  {
    id: 103,
    code: 'CS303',
    name: 'Організація баз даних',
    shortName: 'ОБД',
    fullname: 'Організація баз даних',
    shortname: 'ОБД',
    description:
      'Реляційна модель даних, SQL-запити, транзакції, індексація, нормалізація схем та NoSQL сховища.',
    credits: 4,
    semester: 5,
    academicYear: '2026/2027',
    cycle: 'professional',
    controlType: 'exam',
    instructors: [{ name: 'Доц. Петренко В. О.', email: 'petrenko@karazin.ua', role: 'Лектор' }],
    status: 'in_progress',
    progress: 70,
  },
  {
    id: 104,
    code: 'CS304',
    name: 'Архітектура компʼютерів',
    shortName: 'АК',
    fullname: 'Архітектура компʼютерів',
    shortname: 'АК',
    description:
      'Організація процесорів, конвеєризація, ієрархія памʼяті, кеш-памʼять та асемблер x86/ARM.',
    credits: 4,
    semester: 5,
    academicYear: '2026/2027',
    cycle: 'professional',
    controlType: 'differentiated_credit',
    instructors: [{ name: 'Проф. Сидоренко А. П.', email: 'sydorenko@karazin.ua', role: 'Лектор' }],
    status: 'in_progress',
    progress: 65,
  },
  {
    id: 105,
    code: 'CS305',
    name: 'Іноземна мова за профспрямуванням',
    shortName: 'ІМ',
    fullname: 'Іноземна мова за профспрямуванням',
    shortname: 'ІМ',
    description:
      'Професійна англійська мова для IT-фахівців, академічне письмо, підготовка наукових публікацій.',
    credits: 3,
    semester: 5,
    academicYear: '2026/2027',
    cycle: 'general',
    controlType: 'credit',
    instructors: [
      { name: 'Старш. викл. Іванова М. В.', email: 'ivanova@karazin.ua', role: 'Викладач' },
    ],
    status: 'in_progress',
    progress: 90,
  },
  {
    id: 106,
    code: 'CS306',
    name: 'Фізичне виховання',
    shortName: 'ФВ',
    fullname: 'Фізичне виховання',
    shortname: 'ФВ',
    description: 'Оздоровча та загальнофізична підготовка студентів.',
    credits: 2,
    semester: 5,
    academicYear: '2026/2027',
    cycle: 'general',
    controlType: 'credit',
    instructors: [
      { name: 'Викл. Шевченко О. Д.', email: 'shevchenko@karazin.ua', role: 'Викладач' },
    ],
    status: 'in_progress',
    progress: 95,
  },
];

export const mockFallbackGrades = [
  {
    courseName: 'Паралельні та розподілені обчислення',
    credits: 5,
    currentScore: 56,
    examScore: 38,
    totalScore: 94,
    controlType: 'exam',
    grade: '94',
  },
  {
    courseName: 'Алгоритми та структури даних',
    credits: 5,
    currentScore: 52,
    examScore: 39,
    totalScore: 91,
    controlType: 'exam',
    grade: '91',
  },
  {
    courseName: 'Організація баз даних',
    credits: 4,
    currentScore: 48,
    examScore: 34,
    totalScore: 82,
    controlType: 'exam',
    grade: '82',
  },
  {
    courseName: 'Архітектура компʼютерів',
    credits: 4,
    currentScore: 45,
    examScore: 32,
    totalScore: 77,
    controlType: 'differentiated_credit',
    grade: '77',
  },
  {
    courseName: 'Іноземна мова за профспрямуванням',
    credits: 3,
    currentScore: 85,
    examScore: null,
    totalScore: 85,
    controlType: 'credit',
    grade: '85',
  },
  {
    courseName: 'Фізичне виховання',
    credits: 2,
    currentScore: 75,
    examScore: null,
    totalScore: 75,
    controlType: 'credit',
    grade: '75',
  },
];

export const cardMotion = {
  whileHover: { scale: 1.02, y: -2 },
  whileTap: { scale: 0.98 },
  transition: { duration: 0.15 },
} as const;
